n = int(input())
n_inicial = n
notas_cem = int(n / 100)
resto = n - (notas_cem * 100)
notas_cinquenta = int(resto / 50)
resto = resto - (notas_cinquenta * 50)
notas_vinte = int(resto / 20)
resto = resto - (notas_vinte * 20)
notas_dez = int(resto / 10)
resto = resto - (notas_dez * 10)
notas_cinco = int(resto / 5)
resto = resto - (notas_cinco * 5)
notas_dois = int(resto / 2)
resto = resto - (notas_dois * 2)
notas_um = int(resto)

print(n_inicial)
print(f"{notas_cem} nota(s) de R$ 100,00")
print(f"{notas_cinquenta} nota(s) de R$ 50,00")
print(f"{notas_vinte} nota(s) de R$ 20,00")
print(f"{notas_dez} nota(s) de R$ 10,00")
print(f"{notas_cinco} nota(s) de R$ 5,00")
print(f"{notas_dois} nota(s) de R$ 2,00")
print(f"{notas_um} nota(s) de R$ 1,00")


